# Generated by Django 4.0.4 on 2022-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
