# Generated by Django 4.0.4 on 2022-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_code_product_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_title',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
