# Generated by Django 4.0.4 on 2022-05-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_name_product_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='title',
        ),
    ]
