# Generated by Django 4.0.4 on 2022-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('goods_ids', models.ManyToManyField(related_name='goods_ids', to='products.product')),
            ],
        ),
    ]
